# Generated by Django 3.2.6 on 2021-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_res',
            field=models.BooleanField(default=False, verbose_name='restaurant status'),
        ),
    ]
