# Generated by Django 3.2.6 on 2021-09-27 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_user_is_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=40)),
                ('cuisine', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('zip_code', models.IntegerField()),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
